# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    cmds:
      - rm -f "cmd/kademlia"
      - go build -o cmd/kademlia
  run:
    deps: [build]
    cmds:
      - ./cmd/kademlia
  test:
    cmds:
      - go test -C kademlia
